name: Captura de Carteira Investidor10

on:
  schedule:
    - cron: '0 3 * * *'     # 00:00 BRT (UTC+3)
    - cron: '13 13 * * *'   # 10:30 BRT
    - cron: '20 20 * * *'   # 17:00 BRT
  workflow_dispatch:        # Permite execução manual

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Executar scraper às 00:00
        if: github.event.schedule == '0 3 * * *'
        run: python investidor10_scraper.py "00:00"

      - name: Executar scraper às 10:30
        if: github.event.schedule == '13 13 * * *'
        run: python investidor10_scraper.py "10:30"

      - name: Executar scraper às 17:00
        if: github.event.schedule == '20 20 * * *'
        run: python investidor10_scraper.py "17:00"

      - name: Armazenar resultados
        uses: actions/upload-artifact@v4
        with:
          name: htmls-carteira-${{ github.run_id }}
          path: data/
