name: Captura de Carteira Investidor10

on:
  schedule:
    - cron: '0 3 * * *'     # 00:00 BRT (UTC+3)
    - cron: '13 13 * * *'   # 10:30 BRT
    - cron: '20 20 * * *'   # 17:00 BRT
  workflow_dispatch:        # Permite execução manual

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 lxml
          playwright install chromium

      - name: Executar scraper
        run: |
          python investidor10_scraper.py "scheduled"

      - name: Processar HTML para JSON
        run: |
          python parse_html_to_json.py "scheduled"

      - name: Armazenar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: carteira-${{ github.run_id }}
          path: data/
