name: Captura de Carteira Investidor10

on:
  schedule:
    - cron: '0 20 * * *'   # 17:00 BRT (UTC+3)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 lxml
          playwright install chromium

      - name: Executar scraper
        run: python investidor10_scraper.py "scheduled"

      - name: Gerar JSON a partir do HTML
        run: python parse_html_to_json.py "scheduled"

      - name: Salvar JSON no repositório
        run: |
          mkdir -p dados
          cp data/html_raw_scheduled.json dados/$(date +"%Y-%m-%d").json

      - name: Commit e Push do JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase
          git add dados/
          git commit -m "Atualiza JSON da carteira - $(date +"%Y-%m-%d")" || echo "Nada para commitar"
          git push
