name: Captura de Carteira Investidor10

on:
  schedule:
    - cron: '0 3 * * *'     # 00:00 BRT (UTC+3)
    - cron: '13 13 * * *'   # 10:30 BRT
    - cron: '20 20 * * *'   # 17:00 BRT
  workflow_dispatch:
    inputs:
      horario:
        description: 'Horário da execução (00:00, 10:30 ou 17:00)'
        required: false

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Executar scraper
        run: python investidor10_scraper.py "${{ env.HORARIO }}"
        env:
          HORARIO: ${{ github.event.inputs.horario || '17:00' }}

      - name: Armazenar resultados
        uses: actions/upload-artifact@v4
        with:
          name: htmls-carteira-${{ github.run_id }}
          path: data/
