name: Gerar Relatório Diário

on:
  schedule:
    - cron: '10 20 * * *'  # 17:10 BRT (20:10 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  gerar-relatorio:
    runs-on: ubuntu-latest
    name: Gerar Relatório Diário

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script de geração de relatório
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/gerar_relatorio.py
